language: ruby
bundler_args: --without development
env:
  - CI=true
before_script:
 - "bundle exec rake db:prepare"

rvm:
  - 1.8.7
  - 1.9.2
  - rbx-18mode
  - rbx-19mode
  - ree
  - jruby-18mode

gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile

notifications:
  recipients:
    - gabriel.sobrinho@gmail.com
    - thiago.pradi@gmail.com
