production:
  shards:
    history_shards:
      aug2009:
        adapter: mysql
        host: localhost
        database: teste2
      aug2010:
        adapter: mysql
        host: localhost
        database: teste3
      aug2011:
        adapter: mysql
        host: localhost
        database: teste4
    
    country_shards:
      canada:
        adapter: mysql
        host: localhost
        database: teste2
      brazil:
        adapter: mysql
        host: localhost
        database: teste3
      russia:
        adapter: mysql
        host: localhost
        database: teste4