test:
  shards:
    canada:
      adapter: mysql
      host: localhost
      database: teste2
    brazil:
      adapter: mysql
      host: localhost
      database: teste2
    russia:
      adapter: mysql
      host: localhost
      database: teste3